# DiscordMC by manuelgu
# https://www.spigotmc.org/resources/17067/
settings:
  token: 'MTkyMzU1NDIxNzcwNjEyNzM3.C2goTg.gS2Fl4zG-CkNYMI1eeI7Ejm5zUk'
  send_game_login: true
  send_game_logout: true
  send_game_chat: true
  send_discord_chat: true
  send_death_message: true
  use_nicknames: true
  use_mentions: true
  check_for_updates: true
  templates:
    chat_message_discord: '<%user> %message'
    player_join_minecraft: '%user joined the game'
    player_leave_minecraft: '%user left the game'
    chat_message_minecraft: '&9Î´&r <%user> %message'
  channels:
    minecraft_to_discord:
      - 'survival'
    discord_to_minecraft:
      - 'survival'
  discord_commands:
    enabled: true
    command_prefix: '?'
